version: '3.8'

services:
  funcion-usuarios:
    build:
      context: .
      dockerfile: funcion-usuarios/Dockerfile
    container_name: funcion-usuarios
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - DB_URL=jdbc:oracle:thin:@(description=(retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1522)(host=adb.sa-santiago-1.oraclecloud.com))(connect_data=(service_name=g64afca1579a0d2_s58onuxcx4c1qxe9_high.adb.oraclecloud.com))(security=(ssl_server_dn_match=yes)))
      - DB_USER=biblioteca
      - DB_PASSWORD=#Ng3naUQa*THhTd
      - ORACLE_NET_TNS_ADMIN=/app/wallet
    volumes:
      - ./wallet:/app/wallet:ro
    networks:
      - biblioteca-network
    restart: unless-stopped

  funcion-prestamos:
    build:
      context: .
      dockerfile: funcion-prestamos/Dockerfile
    container_name: funcion-prestamos
    ports:
      - "8082:8082"
    environment:
      - PORT=8082
      - DB_URL=jdbc:oracle:thin:@(description=(retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1522)(host=adb.sa-santiago-1.oraclecloud.com))(connect_data=(service_name=g64afca1579a0d2_s58onuxcx4c1qxe9_high.adb.oraclecloud.com))(security=(ssl_server_dn_match=yes)))
      - DB_USER=biblioteca
      - DB_PASSWORD=#Ng3naUQa*THhTd
      - ORACLE_NET_TNS_ADMIN=/app/wallet
    volumes:
      - ./wallet:/app/wallet:ro
    networks:
      - biblioteca-network
    restart: unless-stopped

  microservicio-bff:
    build:
      context: ./microservicio-bff
      dockerfile: Dockerfile
    container_name: microservicio-bff
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - USUARIOS_SERVICE_URL=http://funcion-usuarios:8081
      - PRESTAMOS_SERVICE_URL=http://funcion-prestamos:8082
    depends_on:
      - funcion-usuarios
      - funcion-prestamos
    networks:
      - biblioteca-network
    restart: unless-stopped

networks:
  biblioteca-network:
    driver: bridge
