server.port=${PORT:8080}
spring.application.name=biblioteca-bff

serverless.usuarios.url=${USUARIOS_SERVICE_URL:http://localhost:8081}
serverless.prestamos.url=${PRESTAMOS_SERVICE_URL:http://localhost:8082}

logging.level.com.biblioteca.bff=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
